---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: vehicle-fleet-demo

outputs:
- name: build-output

params:
  TERM: dumb

caches:
- path: project/.m2repository

run:
  path: vehicle-fleet-demo/ci/tasks/build-service/task.sh
