/*
 * Copyright 2015 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package demo;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A POJO representation of a truck on the road.
 *
 * Auto-generated by http://www.jsonschema2pojo.org/.
 *
 * @author Dave Syer
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Entity
public class Location {

	enum GpsStatus {
		EXCELLENT,OK,UNRELIABLE,BAD,NOFIX,UNKNOWN;
	}

	enum VehicleMovementType {
		STOPPED, IN_MOTION;
		public boolean isMoving() {
			return this != STOPPED;
		}
	}

	@Id
	@GeneratedValue
	private Long id;
	@Embedded
	@AttributeOverride(name = "engineMake", column = @Column(name = "unit_engine_make"))
	private UnitInfo unitInfo;
	@Embedded
	@AttributeOverrides({
		@AttributeOverride(name = "fmi", column = @Column(name = "unit_fmi")),
		@AttributeOverride(name = "spn", column = @Column(name = "unit_spn")) })
	private UnitFault unitFault;
	private double latitude;
	private double longitude;
	private String heading;
	private double gpsSpeed;
	private GpsStatus gpsStatus;
	private double odometer;
	private double totalEngineTime;
	private double totalIdleTime;
	private double totalFuelUsage;
	private String address;
	private Date timestamp = new Date();
	private String tspProvider;
	private VehicleMovementType vehicleMovementType = VehicleMovementType.STOPPED;
	private String serviceType;
	// TODO: why is this not part of UnitFault?
	@Embedded
	private FaultCode faultCode;

	@SuppressWarnings("unused")
	private Location() {
		this.unitInfo = null;
	}

	@JsonCreator
	public Location(@JsonProperty("unitInfo") UnitInfo unitInfo,
					@JsonProperty("unitFault") UnitFault unitFault,
					@JsonProperty("latitude") double latitude,
					@JsonProperty("longitude") double longitude,
					@JsonProperty("heading") String heading,
					@JsonProperty("gpsSpeed") double gpsSpeed,
					@JsonProperty("gpsStatus") GpsStatus gpsStatus,
					@JsonProperty("odometer") double odometer,
					@JsonProperty("totalEngineTime") double totalEngineTime,
					@JsonProperty("totalIdleTime") double totalIdleTime,
					@JsonProperty("totalFuelUsage") double totalFuelUsage,
					@JsonProperty("address") String address,
					@JsonProperty("timestamp") Date timestamp,
					@JsonProperty("tspProvider") String tspProvider,
					@JsonProperty("vehicleMovementType") VehicleMovementType vehicleMovementType,
					@JsonProperty("serviceType") String serviceType,
					@JsonProperty("faultCode") FaultCode faultCode,
					@JsonProperty("vin") String vin) {

		this.unitInfo = unitInfo != null ? unitInfo : new UnitInfo(vin);
		this.unitFault = unitFault;
		this.latitude = latitude;
		this.longitude = longitude;
		this.heading = heading;
		this.gpsSpeed = gpsSpeed;
		this.gpsStatus = gpsStatus;
		this.odometer = odometer;
		this.totalEngineTime = totalEngineTime;
		this.totalIdleTime = totalIdleTime;
		this.totalFuelUsage = totalFuelUsage;
		this.address = address;
		this.timestamp = timestamp;
		this.tspProvider = tspProvider;
		this.vehicleMovementType = vehicleMovementType;
		this.serviceType = serviceType;
		this.faultCode = faultCode;
	}

	protected Location(String vin) {
		this.unitInfo = new UnitInfo(vin);
	}

	protected Location(UnitInfo unitInfo) {
		this.unitInfo = unitInfo;
	}

	public String getVin() {
		return this.unitInfo == null ? null : this.unitInfo.getUnitVin();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UnitInfo getUnitInfo() {
		return unitInfo;
	}

	public void setUnitInfo(UnitInfo unitInfo) {
		this.unitInfo = unitInfo;
	}

	public UnitFault getUnitFault() {
		return unitFault;
	}

	public void setUnitFault(UnitFault unitFault) {
		this.unitFault = unitFault;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public String getHeading() {
		return heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	public double getGpsSpeed() {
		return gpsSpeed;
	}

	public void setGpsSpeed(double gpsSpeed) {
		this.gpsSpeed = gpsSpeed;
	}

	public GpsStatus getGpsStatus() {
		return gpsStatus;
	}

	public void setGpsStatus(GpsStatus gpsStatus) {
		this.gpsStatus = gpsStatus;
	}

	public double getOdometer() {
		return odometer;
	}

	public void setOdometer(double odometer) {
		this.odometer = odometer;
	}

	public double getTotalEngineTime() {
		return totalEngineTime;
	}

	public void setTotalEngineTime(double totalEngineTime) {
		this.totalEngineTime = totalEngineTime;
	}

	public double getTotalIdleTime() {
		return totalIdleTime;
	}

	public void setTotalIdleTime(double totalIdleTime) {
		this.totalIdleTime = totalIdleTime;
	}

	public double getTotalFuelUsage() {
		return totalFuelUsage;
	}

	public void setTotalFuelUsage(double totalFuelUsage) {
		this.totalFuelUsage = totalFuelUsage;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getTspProvider() {
		return tspProvider;
	}

	public void setTspProvider(String tspProvider) {
		this.tspProvider = tspProvider;
	}

	public VehicleMovementType getVehicleMovementType() {
		return vehicleMovementType;
	}

	public void setVehicleMovementType(VehicleMovementType vehicleMovementType) {
		this.vehicleMovementType = vehicleMovementType;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public FaultCode getFaultCode() {
		return faultCode;
	}

	public void setFaultCode(FaultCode faultCode) {
		this.faultCode = faultCode;
	}

	@Override
	public String toString() {
		return "Location{" +
				"id=" + id +
				", unitInfo=" + unitInfo +
				", unitFault=" + unitFault +
				", latitude=" + latitude +
				", longitude=" + longitude +
				", heading='" + heading + '\'' +
				", gpsSpeed=" + gpsSpeed +
				", gpsStatus=" + gpsStatus +
				", odometer=" + odometer +
				", totalEngineTime=" + totalEngineTime +
				", totalIdleTime=" + totalIdleTime +
				", totalFuelUsage=" + totalFuelUsage +
				", address='" + address + '\'' +
				", timestamp=" + timestamp +
				", tspProvider='" + tspProvider + '\'' +
				", vehicleMovementType=" + vehicleMovementType +
				", serviceType='" + serviceType + '\'' +
				", faultCode=" + faultCode +
				'}';
	}
}
